// Code generated by go-bindata. DO NOT EDIT.
// sources:
// ../../../transactions/mint_nft.cdc (1.089kB)
// ../../../transactions/setup_account.cdc (804B)
// ../../../transactions/transfer_nft.cdc (1.091kB)

package assets

import (
	"bytes"
	"compress/gzip"
	"crypto/sha256"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data, name string) ([]byte, error) {
	gz, err := gzip.NewReader(strings.NewReader(data))
	if err != nil {
		return nil, fmt.Errorf("read %q: %w", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)

	if err != nil {
		return nil, fmt.Errorf("read %q: %w", name, err)
	}

	clErr := gz.Close()
	if clErr != nil {
		return nil, clErr
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes  []byte
	info   os.FileInfo
	digest [sha256.Size]byte
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _TransactionsMint_nftCdc = "\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x84\x53\xcd\x8e\xd3\x30\x10\xbe\xe7\x29\x46\x3d\x40\x7a\x69\x38\x57\xb0\xab\xd2\x25\x68\x0f\x64\x11\x9b\x17\x70\x9c\x69\x32\xc2\xb1\x23\x7b\xbc\x5d\x54\xf5\xdd\x91\xf3\x9f\xaa\x82\x5e\x1a\xc9\x33\xdf\xaf\x4d\x4d\x6b\x2c\x43\x66\x74\xea\x75\x45\x85\xc2\xdc\xfc\x46\x0d\x27\x6b\x1a\xf8\xf4\x9e\xa5\xf9\xe1\xe9\xe9\xd7\xb7\xd7\xd7\x68\x98\x3c\x9a\x8a\xd8\x8c\xe7\xc7\x97\xef\xcf\xf9\xcb\x38\x12\x25\x09\xe4\x35\x39\x70\xd2\x52\xcb\xe0\x1d\x3a\xe0\x1a\x87\xa5\x1f\xa4\x19\x2d\x58\x74\xc6\x5b\x89\xc0\x06\x1a\xd2\x0c\x02\x34\x9e\x47\xe0\x2c\xcd\x03\xcc\x33\x43\xe3\x1d\x43\x81\x60\xbd\x86\x33\x71\xdd\x21\x09\x29\x8d\xd7\x0c\x5c\x0b\x86\x5a\xf4\xf0\xcd\x1a\x38\xec\x3b\x36\x16\x4b\x20\x0d\x49\xf8\x14\x15\x26\x4b\x11\x51\xc4\x56\x68\x27\x24\x93\xd1\xb1\x45\x49\x2d\xa1\xe6\x3d\x1c\xca\xd2\xa2\x73\x5b\xb8\x44\x11\x00\x40\x92\x80\x32\x52\x28\x78\x13\x96\x44\xa1\x10\x4e\xc6\x76\xe8\xa4\xab\x35\xf9\x09\x2d\x6a\x89\xdd\x9a\x42\x1e\x0e\xf6\xf0\xa1\x27\xde\xad\xf9\xc3\x54\x6b\xb1\x15\x16\x63\x47\x95\x0e\x93\x07\xcf\xf5\xa1\x37\x38\x09\x18\x44\x14\xc6\x5a\x73\x06\x31\xf3\x84\xf8\x02\x7f\x96\xe6\xb7\xc1\x92\x86\xc1\xf4\x04\xe1\x50\x9d\x76\x83\xd4\x2f\xd0\x13\xee\x7a\xd0\xcf\xf7\x04\x3e\xc4\xa1\xe1\xfd\xfd\xf4\xb6\x13\x6c\xf8\x3d\x3e\x42\x2b\x34\xc9\x78\x73\x34\x5e\x95\xa0\x0d\xff\x5b\xee\x90\xcc\xa6\x87\xb9\xf6\x3e\xf1\x1d\xa5\x67\x84\xcb\xd2\xf5\xd7\x1e\x26\xec\x4d\x1d\x7d\x74\xd0\xfa\x42\x91\xec\xa0\xa4\x51\x0a\xbb\x16\x6f\x1a\x18\x5b\xb0\x28\x91\xde\x3a\xd7\x15\xf2\x90\xee\xdc\xf8\xda\xca\xae\x42\x3e\x8a\x56\x14\xa4\x88\xff\xc4\x49\x4f\x34\x78\x3f\x4e\x54\x37\x4b\x63\x8c\x97\xdb\x57\xb4\x9b\x57\x7e\x76\x48\xd7\x87\xf8\xff\xd9\x55\x4b\xd5\x77\xf3\x9b\x61\x37\xdb\xd5\x2d\x09\xf5\x4c\x53\x42\x97\x50\x62\x6b\x1c\x31\x10\x8f\xfb\xcb\x1c\xe7\xf0\xee\xdd\x93\xee\x2f\x4b\xf3\xe5\xf3\x18\x75\x8d\xd5\x5d\xa3\xbf\x01\x00\x00\xff\xff\xf4\x6e\xb9\x6d\x41\x04\x00\x00"

func TransactionsMint_nftCdcBytes() ([]byte, error) {
	return bindataRead(
		_TransactionsMint_nftCdc,
		"../../../transactions/mint_nft.cdc",
	)
}

func TransactionsMint_nftCdc() (*asset, error) {
	bytes, err := TransactionsMint_nftCdcBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "../../../transactions/mint_nft.cdc", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0x37, 0x40, 0xb, 0xb1, 0x59, 0xf6, 0x57, 0x85, 0x7c, 0xdb, 0xe4, 0x92, 0x80, 0x29, 0x3e, 0x68, 0x90, 0x7e, 0x94, 0x86, 0x5d, 0x47, 0x23, 0x1f, 0xbc, 0x9e, 0x3, 0xbf, 0x5b, 0xfc, 0xd2, 0x62}}
	return a, nil
}

var _TransactionsSetup_accountCdc = "\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x7c\x92\xcf\x6e\xda\x40\x10\xc6\xef\x7e\x8a\xaf\x97\xc8\x48\x09\xee\x39\xa2\x91\x10\x09\x55\x2f\xa4\x4a\xfc\x02\xc3\x66\x8c\x57\x59\x76\xad\xd9\x71\x28\x42\xbc\x7b\xb5\x76\x30\xb8\x8d\xd8\xe3\xfa\x37\xf3\xfd\x59\xdb\x6d\x13\x44\xb1\x0a\x7e\xd9\xfa\x8d\x5d\x3b\x2e\xc3\x3b\x7b\x54\x12\xb6\xf8\xfe\x67\xb5\x2c\xe7\x8f\x8f\x2f\x4f\xaf\xaf\xd9\x27\xb9\x08\x1b\xab\xe1\xf4\x7d\xf1\xfc\xf3\x57\xf9\x7c\x42\x8a\x02\x65\x6d\x23\x54\xc8\x47\x32\x6a\x83\x87\x8d\xd8\xd5\xa4\x20\x0f\x32\x26\xb4\x5e\xb1\x0b\xad\x7b\x83\xb4\x3e\x0d\x68\x40\x64\x85\xd5\xc8\xae\x42\xdb\xa4\x0b\x61\xc3\xf6\x83\xb1\x5a\x96\x31\xcb\x2e\xb7\x1d\xb2\x0c\x00\x1a\xe1\x86\x84\x73\x32\x46\xef\x31\x6f\xb5\x9e\xf7\xbb\x27\x27\x22\x9d\xa2\xc0\x0b\x6b\x2b\x1e\x4c\xe2\xf6\xb0\x15\xb4\xe6\xc1\x06\x39\x61\x7a\xdb\xa3\xa6\x08\x82\x09\xce\x71\x27\x32\xcc\xdb\x2a\xb1\x3a\x5d\x07\x91\xb0\x9b\xdd\xf4\xd1\xa7\x8b\x81\x7c\xc8\x53\x0d\xf7\x28\xa2\x06\xa1\x0d\x17\x3d\x71\x06\x26\xf8\xf6\x03\xde\x3a\x1c\x86\xa5\xe9\x48\xe7\x6a\xb8\x3a\x8e\x2c\x2f\x84\x49\x19\x04\xcf\x3b\xf0\xb6\xd1\xfd\x57\xde\x1c\xeb\xc5\x35\x66\x77\x9f\x0f\x33\x35\xdd\xf8\x53\x9a\x3b\xfb\xc8\x27\x23\x89\x48\x1f\x0c\xab\xa9\xea\x8b\x42\x06\xa2\x0b\x9d\x98\x7c\x76\x77\xd6\xb8\x85\x86\x6b\x51\x47\x0a\xe6\x14\xa2\x69\xd7\xce\x1a\x18\x6a\x68\x6d\x9d\xd5\x3d\xaa\x20\x9d\xea\x17\xa1\x3a\x61\x67\xfd\xfb\xec\xe6\xf0\xef\x1f\x79\x51\xfb\xef\x6e\xe7\xf1\x21\x1f\x95\x5a\xf4\x52\xff\x19\xbb\x1d\x51\x4a\xb2\x61\xbd\x92\x63\xa0\x27\x59\xff\x36\xc7\xec\x6f\x00\x00\x00\xff\xff\x8c\x06\xf0\x6b\x24\x03\x00\x00"

func TransactionsSetup_accountCdcBytes() ([]byte, error) {
	return bindataRead(
		_TransactionsSetup_accountCdc,
		"../../../transactions/setup_account.cdc",
	)
}

func TransactionsSetup_accountCdc() (*asset, error) {
	bytes, err := TransactionsSetup_accountCdcBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "../../../transactions/setup_account.cdc", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0xe6, 0xc0, 0x66, 0xe7, 0xc0, 0xbf, 0xcf, 0xc, 0x63, 0xc6, 0xcf, 0xd8, 0x91, 0x51, 0xdf, 0x2b, 0x7a, 0x75, 0xc5, 0x0, 0xc9, 0x1c, 0xd5, 0x7c, 0x97, 0xc6, 0x1a, 0x32, 0x2a, 0xb1, 0x87, 0x3c}}
	return a, nil
}

var _TransactionsTransfer_nftCdc = "\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\xa4\x93\xc1\x6e\xd3\x40\x10\x86\xef\x7e\x8a\x51\x0f\xe0\x48\x34\xe6\x80\x38\x44\x69\xab\x28\x21\x28\x97\x14\xb5\xe6\x01\xd6\xeb\xb1\xbd\xe0\xee\x58\xb3\x63\x02\xaa\xf2\xee\x68\xbd\xb1\x1d\x03\x29\x87\xfa\xb4\xda\xcc\xfc\xff\xfc\xdf\x4e\xcc\x53\x43\x2c\xb0\x27\xbb\x6d\x6d\x69\xb2\x1a\x53\xfa\x8e\x16\x0a\xa6\x27\x78\xff\x73\xbf\x4d\x57\x9b\xcd\xc3\xa7\xc7\xc7\xe8\x54\xb9\xa6\xd2\x08\xf5\xbf\xaf\xef\x3f\xef\xd2\xfb\xbe\x24\x4a\x12\x48\x2b\xe3\x40\x58\x59\xa7\xb4\x18\xb2\x60\x1c\x14\xc4\xe1\xaa\x40\x66\x63\x4b\x50\x36\x87\xfd\x36\xed\x54\x7c\x13\x59\x04\xa5\x35\xb5\x56\x40\x08\x94\x25\xa9\x90\xa3\xe8\x4c\x27\x66\xd4\xa6\x31\x68\x65\x01\xab\x3c\x67\x74\xee\x1d\x1c\x8c\x54\x39\xab\xc3\x6e\xb3\x80\xaf\x3b\x2b\x1f\x3f\xcc\xe0\x39\x8a\x00\x00\x1a\xc6\x46\x31\xc6\x4a\x6b\xdf\xd1\x4a\xb5\x0a\x06\x43\x85\xff\x92\x04\x4a\x14\x90\x0a\x61\xd0\x77\xd0\xb4\x59\x6d\xf4\x30\x11\x65\xdf\x50\xcb\xd0\x53\xa3\x8c\xc5\x70\xe3\x05\x4e\xd2\xe3\x8c\xb3\x89\x45\x46\xcc\x74\x00\x05\x8c\x05\x32\x5a\x8d\x3e\xa5\x37\x75\xa6\xb4\xc8\x6f\x5d\x47\x43\x53\x5d\x63\x17\x76\xe2\x35\x5e\x3f\x60\x01\x37\x7e\x2c\x99\x07\xc9\xe5\x9b\xf0\x1c\xf3\xf5\x50\x73\x1b\x7b\xa8\x0b\x48\x9c\x10\xab\x12\x93\x50\x31\x16\xcc\x06\x71\xff\xdd\xdd\x41\xa3\xac\xd1\xf1\xd5\x9a\xda\x3a\x07\x4b\xf2\xc2\xb8\x74\x08\xd3\x8e\x23\x5d\x5d\x48\x7a\x42\xf8\x97\x02\xa3\x46\xf3\x03\xd9\x5d\x4a\x9b\x63\x43\xce\x48\x88\x3a\xf0\x9c\x97\x28\x6b\xd5\xa8\xcc\xd4\x46\x7e\xc5\x49\x90\xff\x4f\xb6\x01\xd2\xf3\x9f\xeb\x7d\xc6\xeb\x4b\xa7\x74\xbc\x8d\x5f\xc3\xa5\x4f\xf5\x12\x9a\x7e\x57\xbb\x86\x7e\xf9\x2f\x50\x9d\x10\xb1\x85\xc0\xf2\x7a\xba\x06\xf3\x5e\x2d\x3e\xff\x0b\x8c\xe7\xa9\xf5\x26\x30\x1d\x9c\x8d\x9d\x6e\xfc\xbf\xbd\xc7\x97\x98\x9f\x8e\xb1\x78\x78\x0b\x58\x5e\xdb\x42\x02\xaf\x63\x74\xfc\x1d\x00\x00\xff\xff\xf0\xa1\x8f\x63\x43\x04\x00\x00"

func TransactionsTransfer_nftCdcBytes() ([]byte, error) {
	return bindataRead(
		_TransactionsTransfer_nftCdc,
		"../../../transactions/transfer_nft.cdc",
	)
}

func TransactionsTransfer_nftCdc() (*asset, error) {
	bytes, err := TransactionsTransfer_nftCdcBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "../../../transactions/transfer_nft.cdc", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0xbf, 0xcf, 0x5, 0x7d, 0x7, 0x3, 0x68, 0x8f, 0x6c, 0xaa, 0x67, 0x8a, 0xbb, 0x3b, 0x7d, 0x60, 0xe0, 0x6b, 0x65, 0xc, 0xc5, 0x7f, 0x99, 0x1f, 0xc, 0x6b, 0xa0, 0xb5, 0xac, 0xed, 0xa0, 0x15}}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// AssetString returns the asset contents as a string (instead of a []byte).
func AssetString(name string) (string, error) {
	data, err := Asset(name)
	return string(data), err
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// MustAssetString is like AssetString but panics when Asset would return an
// error. It simplifies safe initialization of global variables.
func MustAssetString(name string) string {
	return string(MustAsset(name))
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetDigest returns the digest of the file with the given name. It returns an
// error if the asset could not be found or the digest could not be loaded.
func AssetDigest(name string) ([sha256.Size]byte, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return [sha256.Size]byte{}, fmt.Errorf("AssetDigest %s can't read by error: %v", name, err)
		}
		return a.digest, nil
	}
	return [sha256.Size]byte{}, fmt.Errorf("AssetDigest %s not found", name)
}

// Digests returns a map of all known files and their checksums.
func Digests() (map[string][sha256.Size]byte, error) {
	mp := make(map[string][sha256.Size]byte, len(_bindata))
	for name := range _bindata {
		a, err := _bindata[name]()
		if err != nil {
			return nil, err
		}
		mp[name] = a.digest
	}
	return mp, nil
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"../../../transactions/mint_nft.cdc":      TransactionsMint_nftCdc,
	"../../../transactions/setup_account.cdc": TransactionsSetup_accountCdc,
	"../../../transactions/transfer_nft.cdc":  TransactionsTransfer_nftCdc,
}

// AssetDebug is true if the assets were built with the debug flag enabled.
const AssetDebug = false

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"},
// AssetDir("data/img") would return []string{"a.png", "b.png"},
// AssetDir("foo.txt") and AssetDir("notexist") would return an error, and
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		canonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(canonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{nil, map[string]*bintree{
	"..": {nil, map[string]*bintree{
		"..": {nil, map[string]*bintree{
			"..": {nil, map[string]*bintree{
				"transactions": {nil, map[string]*bintree{
					"mint_nft.cdc": {TransactionsMint_nftCdc, map[string]*bintree{}},
					"setup_account.cdc": {TransactionsSetup_accountCdc, map[string]*bintree{}},
					"transfer_nft.cdc": {TransactionsTransfer_nftCdc, map[string]*bintree{}},
				}},
			}},
		}},
	}},
}}

// RestoreAsset restores an asset under the given directory.
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	return os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
}

// RestoreAssets restores an asset under the given directory recursively.
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(canonicalName, "/")...)...)
}
